name: Development Workflow

on:
  push:
    branches:
      - dev
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v5
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.x'
            architecture: 'x64'
        - name: Display Python version
          run: python -c "import sys; print(sys.version)"
        #instaling uv
        - name: Install uv
          uses: astral-sh/setup-uv@v7

        # installing dependencies
        - name: Install dependencies  
          run: uv pip install cryptography

        # running tests
        - name: Run tests
          run: python program.py 